spring:
  application:
    name: hrworkers
  
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/MS_COURSE
      username: postgres
      password: vicente0301
      driverClassName: org.postgresql.Driver
